version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5434;Database=ferramentagestao;Username=postgres;Password=135798As@357;
    ports:
      - "5002:8080"
    restart: always

  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=135798As@357
      - POSTGRES_DB=ferramentagestao
    ports:
      - "5434:5432"
    volumes:
    - ./new_data_directory:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
    
