version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=amtests;Username=user;Password=135798As@357;
    ports:
      - "5002:8080"
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 135798As@357
      POSTGRES_DB: amtests
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
